#!/bin/bash

printf "\n============================================[ Building Application ]============================================\n\n"
rm -r ./res
\cp -r ../extra/* ./
make
if [ $? -eq 0 ]; then
    printf "\n============================================[ Running Application ]============================================\n\n"
    ./omniax-test
fi